In [10]:
import pandas as pd
import numpy as np

location ="datasets/DC_Properties.csv"
df = pd.read_csv(location)
df.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [11]:
#explore the data - show columns, mean, median,mode, sum etc...
print(df.columns)

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [12]:
print(df.dtypes)

Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE               float64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT          float64
CENSUS_BLOCK           object
WARD                   object
SQUARE                 object
X                     float64
Y                     float64
QUADRANT               object
dtype: object

In [13]:
df.count()

Unnamed: 0            158957
BATHRM                158957
HF_BATHRM             158957
HEAT                  158957
AC                    158957
NUM_UNITS             106696
ROOMS                 158957
BEDRM                 158957
AYB                   158686
YR_RMDL                80928
EYB                   158957
STORIES               106652
SALEDATE              132187
PRICE                  98216
QUALIFIED             158957
SALE_NUM              158957
GBA                   106696
BLDG_NUM              158957
STYLE                 106696
STRUCT                106696
GRADE                 106696
CNDTN                 106696
EXTWALL               106696
ROOF                  106696
INTWALL               106696
KITCHENS              106695
FIREPLACES            158957
USECODE               158957
LANDAREA              158957
GIS_LAST_MOD_DTTM     158957
SOURCE                158957
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  106051
STATE                 106051
ZIPCODE               158956
NATIONALGRID          106051
LATITUDE              158956
LONGITUDE             158956
ASSESSMENT_NBHD       158956
ASSESSMENT_SUBNBHD    126406
CENSUS_TRACT          158956
CENSUS_BLOCK          106051
WARD                  158956
SQUARE                158957
X                     158720
Y                     158720
QUADRANT              158720
dtype: int64

In [14]:
df['ROOMS'].mean()

6.187736306045031

In [15]:
df['ROOMS'].median()

6.0

In [16]:
df['ROOMS'].mode()

0    6
dtype: int64

In [17]:
df['ROOMS'].sum()

983584

In [18]:
df['ROOMS'].std()

2.618164876300674

In [23]:
df.groupby(['CITY', 'STATE']).mean()

,,Unnamed: 0,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,USECODE,LANDAREA,CMPLX_NUM,LIVING_GBA,ZIPCODE,LATITUDE,LONGITUDE,CENSUS_TRACT,X,Y
CITY,STATE,,,,,,,,,,,,,,,,,,,,,
WASHINGTON,DC,53257.851553,2.03222,0.607708,1.197735,7.381335,3.368096,1933.823652,2000.897032,1966.180979,2.093101,...,13.130626,3415.643851,NaN,NaN,20012.047939,38.916736,-77.010124,5550.89242,-77.010161,38.916725

In [25]:
#find missing values / data
filename = "datasets/DC_Properties.csv"
df_missing = pd.read_csv(filename)
df.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [26]:
#'isnull' is a series method used to check for missing or non values.
print(df.isnull().sum())

Unnamed: 0                 0
BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS              52261
ROOMS                      0
BEDRM                      0
AYB                      271
YR_RMDL                78029
EYB                        0
STORIES                52305
SALEDATE               26770
PRICE                  60741
QUALIFIED                  0
SALE_NUM                   0
GBA                    52261
BLDG_NUM                   0
STYLE                  52261
STRUCT                 52261
GRADE                  52261
CNDTN                  52261
EXTWALL                52261
ROOF                   52261
INTWALL                52261
KITCHENS               52262
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106696
LIVING_GBA            106696
FULLADDRESS            52917
CITY                   52906
STATE                  52906
ZIPCODE                    1
NATIONALGRID           52906
LATITUDE                   1
LONGITUDE                  1
ASSESSMENT_NBHD            1
ASSESSMENT_SUBNBHD     32551
CENSUS_TRACT               1
CENSUS_BLOCK           52906
WARD                       1
SQUARE                     0
X                        237
Y                        237
QUADRANT                 237
dtype: int64

In [37]:
print(df.isnull().tail())

        Unnamed: 0  BATHRM  HF_BATHRM   HEAT     AC  NUM_UNITS  ROOMS  BEDRM  \
158952       False   False      False  False  False       True  False  False
158953       False   False      False  False  False       True  False  False
158954       False   False      False  False  False       True  False  False
158955       False   False      False  False  False       True  False  False
158956       False   False      False  False  False       True  False  False

          AYB  YR_RMDL  ...  LONGITUDE  ASSESSMENT_NBHD  ASSESSMENT_SUBNBHD  \
158952  False    False  ...      False            False               False
158953  False    False  ...      False            False               False
158954  False    False  ...      False            False               False
158955  False     True  ...      False            False                True
158956  False     True  ...      False            False                True

        CENSUS_TRACT  CENSUS_BLOCK   WARD  SQUARE      X      Y  QUADRANT
158952         False          True  False   False  False  False     False
158953         False          True  False   False  False  False     False
158954         False          True  False   False  False  False     False
158955         False          True  False   False  False  False     False
158956         False          True  False   False  False  False     False

[5 rows x 49 columns]

In [28]:
#remove / drop rows with missing values
df_dcprops = pd.read_csv ("datasets/DC_Properties.csv")
df_dcprops.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [29]:
df_dcprops_missing = df_dcprops.dropna()
df_dcprops_missing

Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]

In [38]:
#passing a condition to filter the dataframe
df_dcprops[df_dcprops.SALEDATE.isnull()]

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
30,30,2,1,Forced Air,Y,2.0,8,3,1900.0,2004.0,...,-77.033993,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
33,33,2,1,Forced Air,Y,2.0,10,3,1900.0,2004.0,...,-77.033640,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
36,36,3,1,Warm Cool,Y,2.0,10,4,1800.0,1975.0,...,-77.033431,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
38,38,3,1,Forced Air,Y,2.0,9,4,1800.0,2004.0,...,-77.033294,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
39,39,3,1,Warm Cool,Y,2.0,9,4,1976.0,NaN,...,-77.033225,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
51,51,3,0,Forced Air,Y,3.0,9,3,1890.0,2004.0,...,-77.033361,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
53,53,2,1,Warm Cool,Y,2.0,7,4,1890.0,1978.0,...,-77.033644,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
57,57,1,0,Hot Water Rad,Y,1.0,6,3,1885.0,NaN,...,-77.035813,Old City 2,040 E Old City 2,4300.0,004300 2006,Ward 2,191,-77.035454,38.914956,NW
60,60,2,0,Hot Water Rad,N,2.0,9,2,1870.0,1980.0,...,-77.034766,Old City 2,040 E Old City 2,4300.0,004300 2006,Ward 2,191,-77.035454,38.914956,NW
63,63,3,1,Forced Air,Y,2.0,13,5,1900.0,1999.0,...,-77.036164,Old City 2,040 E Old City 2,4300.0,004300 2006,Ward 2,191,-77.035454,38.914956,NW
80,80,2,1,Warm Cool,Y,2.0,11,3,1979.0,NaN,...,-77.037858,Old City 2,040 D Old City 2,4201.0,004201 1002,Ward 2,176,-77.037830,38.916190,NW
83,83,2,1,Warm Cool,Y,2.0,11,3,1979.0,NaN,...,-77.037915,Old City 2,040 D Old City 2,4201.0,004201 1002,Ward 2,176,-77.037830,38.916190,NW
87,87,1,1,Hot Water Rad,Y,2.0,6,3,1865.0,NaN,...,-77.037394,Old City 2,040 D Old City 2,4201.0,004201 1006,Ward 2,177,-77.037221,38.915033,NW
88,88,2,2,Hot Water Rad,N,1.0,8,4,1865.0,NaN,...,-77.037471,Old City 2,040 D Old City 2,4201.0,004201 1006,Ward 2,177,-77.037221,38.915033,NW
104,104,4,1,Warm Cool,Y,1.0,11,6,1900.0,NaN,...,-77.046366,Old City 2,040 D Old City 2,5500.0,005500 1001,Ward 2,92,-77.046148,38.913145,NW
109,109,2,1,Warm Cool,Y,1.0,13,5,1890.0,2004.0,...,-77.045920,Old City 2,040 D Old City 2,5500.0,005500 1005,Ward 2,93,-77.045889,38.912003,NW
111,111,2,2,Warm Cool,Y,2.0,10,5,1885.0,NaN,...,-77.046061,Old City 2,040 D Old City 2,5500.0,005500 1005,Ward 2,93,-77.045889,38.912003,NW
125,125,3,1,Warm Cool,Y,2.0,10,5,1922.0,2007.0,...,-77.045969,Old City 2,040 D Old City 2,5500.0,005500 1004,Ward 2,93,-77.045889,38.912003,NW
147,147,1,1,Warm Cool,Y,1.0,5,2,1939.0,NaN,...,-77.041986,Old City 2,040 D Old City 2,4202.0,004202 1008,Ward 2,134,-77.042719,38.912019,NW
155,155,1,1,Warm Cool,Y,1.0,6,3,1907.0,2012.0,...,-77.038703,Old City 2,040 D Old City 2,4201.0,004201 2000,Ward 1,149,-77.038764,38.918277,NW
159,159,2,0,Warm Cool,Y,1.0,6,3,1900.0,NaN,...,-77.038697,Old City 2,040 D Old City 2,4201.0,004201 2000,Ward 1,149,-77.038764,38.918277,NW
164,164,1,1,Warm Cool,Y,1.0,6,3,1880.0,NaN,...,-77.039058,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
174,174,2,0,Hot Water Rad,N,1.0,8,4,1900.0,NaN,...,-77.034288,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
176,176,1,0,Hot Water Rad,N,1.0,9,2,1895.0,2008.0,...,-77.032450,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158673,158673,2,1,Warm Cool,Y,NaN,6,2,1961.0,NaN,...,-77.014271,Southwest Waterfront,NaN,10500.0,NaN,Ward 6,540,-77.014273,38.880828,SW
158674,158674,2,2,Warm Cool,Y,NaN,10,4,1961.0,NaN,...,-77.014271,Southwest Waterfront,NaN,10500.0,NaN,Ward 6,540,-77.014273,38.880828,SW
158681,158681,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158696,158696,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158698,158698,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158718,158718,2,1,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158721,158721,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158723,158723,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158728,158728,2,1,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158832,158832,2,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158837,158837,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158840,158840,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158842,158842,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158847,158847,2,0,Warm Cool,Y,NaN,6,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158848,158848,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158849,158849,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158859,158859,2,0,Warm Cool,Y,NaN,6,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158860,158860,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158863,158863,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158866,158866,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158872,158872,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158883,158883,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158913,158913,2,1,Forced Air,Y,NaN,4,2,2014.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158917,158917,2,1,Forced Air,Y,NaN,4,2,2014.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158922,158922,1,0,Ht Pump,Y,NaN,5,2,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158923,158923,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158925,158925,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158937,158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW

In [40]:
df_dcprops.dropna(subset=['ROOMS', 'BEDRM', 'BATHRM', 'HF_BATHRM', 
                          'FIREPLACES', 'EYB', 'QUALIFIED'], inplace=True)

print(df_dcprops.isnull().sum())

Unnamed: 0                 0
BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS              52261
ROOMS                      0
BEDRM                      0
AYB                      271
YR_RMDL                78029
EYB                        0
STORIES                52305
SALEDATE               26770
PRICE                  60741
QUALIFIED                  0
SALE_NUM                   0
GBA                    52261
BLDG_NUM                   0
STYLE                  52261
STRUCT                 52261
GRADE                  52261
CNDTN                  52261
EXTWALL                52261
ROOF                   52261
INTWALL                52261
KITCHENS               52262
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106696
LIVING_GBA            106696
FULLADDRESS            52917
CITY                   52906
STATE                  52906
ZIPCODE                    1
NATIONALGRID           52906
LATITUDE                   1
LONGITUDE                  1
ASSESSMENT_NBHD            1
ASSESSMENT_SUBNBHD     32551
CENSUS_TRACT               1
CENSUS_BLOCK           52906
WARD                       1
SQUARE                     0
X                        237
Y                        237
QUADRANT                 237
dtype: int64